version: '3'
services:
  web:
    build: ~/docker/Nginx
    container_name: nginx                     #容器名称
    image: c32_nginx:1.0                         #镜像
    depends_on:                               #依赖
      - php
    ports:                                    #映射端口 宿主机:容器
      - "80:80"
      - "443:443"
    networks:                                 #容器使用网络
      - front-tier
      - back-tier
    volumes:                                  #映射目录 宿主机:容器
      - /home/nginx/conf.d:/etc/nginx/conf.d
      - /home/wwwroot/html:/usr/share/nginx/html
    links:
      - php:php70
  php:
    build: ~/docker/PHP
    container_name: php70
    image: c32_php:1.0
    networks:
      - front-tier
    volumes:
      - /home/wwwroot/html:/usr/share/nginx/html
  mysql:
    build: ~/docker/MySQL
    container_name: mysql
    image: c32_mysql:1.0
    ports:
      - "3306:3306"
    networks:
      - back-tier
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: 'test'
      MYSQL_PASS: 'test'
    volumes:
      - /home/mysql/data/:/var/lib/mysql/
      - /home/mysql/conf.d:/etc/mysql/mysql.conf.d/
networks:
  front-tier:
    driver: bridge
  back-tier:
    driver: bridge
