version: '2'
services:
  web:
    build: ./Nginx
      dockerfile: Dockerfile
    container_name: nginx                     #容器名称
    image: c32_nginx:1.0                         #镜像
    ports:                                    #映射端口 宿主机:容器
      - "80:80"
      - "443:443"
    networks:                                 #容器使用网络
      - frontend
      - backend
networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge