version: '2'
services:
  web:
    #build: .
      #dockerfile: Dockerfile
    container_name: nginx                     #容器名称
    image: c32_nginx:1.0                         #镜像

    networks:                                 #容器使用网络
      - frontend
      - backend
networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge