# Base Image
FROM nginx:1.15

# Author
MAINTAINER c32 amd5@qq.com

# Add to docker and Unpacking
ADD default.conf /etc/nginx/conf.d/default.conf
ADD index1.html /www/index1.html
#RUN cd /usr/share/nginx/ && chmod 755 -R html