# Base Image
FROM php:7.0-fpm

# Author
MAINTAINER c32 amd5@qq.com

# setting time
ENV TZ=Asia/Shanghai
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
#RUN docker-php-ext-install -j$(nproc) gd
#RUN docker-php-ext-install pdo_mysql




# backup
#RUN docker-php-ext-install gd \
#	&& docker-php-ext-install pdo_mysql \
#	&& pecl install /home/redis.tgz && echo "extension=redis.so" > /usr/local/etc/php/conf.d/redis.ini