# Base Image
FROM mritd/shadowsocks

# Author
MAINTAINER c32 amd5@qq.com

# Add to docker and Unpacking
#ADD https://github.com/sqlmapproject/sqlmap/tarball/master /
#RUN tar -zxvf master

# System variable
#ENV sqlmap /usr/bin/sqlmap/sqlmap.py

# Command
CMD echo hello world
ENTRYPOINT echo ni hao


# PORT
EXPOSE 6443